import { Sparkles, ShieldAlert } from "lucide-react";
import type { AssessmentStatus, OverallAssessment } from "../../shared/screeningSchema";
import type { Candidate, HRDecision, Importance, ScreeningStatus } from "../../shared/types";
import { Badge } from "./ui/Badge";
import { ALIGNMENT, ASSESSMENT, DECISION, IMPORTANCE, REVIEW_STATUS, SCREENING_STATUS } from "../utils/labels";

export const AlignmentBadge = ({ value }: { value: OverallAssessment }) => (
  <Badge tone={ALIGNMENT[value].tone} title={ALIGNMENT[value].description}>{ALIGNMENT[value].label}</Badge>
);
export const AssessmentBadge = ({ value }: { value: AssessmentStatus }) => <Badge tone={ASSESSMENT[value].tone}>{ASSESSMENT[value].label}</Badge>;
export const ImportanceBadge = ({ value }: { value: Importance }) => <Badge tone={IMPORTANCE[value].tone}>{IMPORTANCE[value].label}</Badge>;
export const ScreeningStatusBadge = ({ value }: { value: ScreeningStatus }) => <Badge tone={SCREENING_STATUS[value].tone}>{SCREENING_STATUS[value].label}</Badge>;
export const DecisionBadge = ({ value }: { value: HRDecision }) => <Badge tone={DECISION[value].tone}>{DECISION[value].label}</Badge>;

export function ReviewStatusBadge({ review }: { review: Candidate["hrReview"] }) {
  const s = REVIEW_STATUS[review?.status ?? "not_started"];
  return <Badge tone={s.tone}>{s.label}</Badge>;
}

export const VerificationBadge = () => (
  <Badge tone="blue" icon={<ShieldAlert className="size-3" aria-hidden />}>Needs Verification</Badge>
);

export const AIBadge = ({ label = "AI-generated assessment" }: { label?: string }) => (
  <Badge tone="purple" icon={<Sparkles className="size-3" aria-hidden />} title="Generated by Claude. HR is responsible for reviewing and verifying it.">
    {label}
  </Badge>
);

export const DemoBadge = () => <Badge tone="yellow">Demo data</Badge>;
